# Generated by Django 4.2.30 on 2026-05-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brands/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("year", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        default=0, help_text="Mileage in kilometers"
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("certified", "Certified Pre-Owned"),
                        ],
                        default="used",
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("manual", "Manual"),
                            ("cvt", "CVT"),
                            ("semi_auto", "Semi-Automatic"),
                        ],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                            ("plugin_hybrid", "Plug-in Hybrid"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                (
                    "engine_size",
                    models.CharField(
                        blank=True, help_text="e.g. 2.0L, 1600cc", max_length=20
                    ),
                ),
                (
                    "horsepower",
                    models.PositiveIntegerField(
                        blank=True, help_text="Horsepower (HP)", null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="dealership.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="car_images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, help_text="Set as the primary display image"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dealership.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Image",
                "verbose_name_plural": "Car Images",
                "ordering": ["-is_main", "order"],
            },
        ),
    ]
